### ISSUE TITLE
Sugestão: organizar os desafios em uma tabela

### ISSUE THREAD

**Issue by jonatasosilva** [return-forty-two/hacktoberfest-2021-challenges#1]
Desafio | Linguagens Permitidas | Nível
---------|--------------------------|------
[Tabuada](/tabuada/README.md) | Todas | Fácil 
[Recursão](/recursao/README.md) | Elixir | Difícil

```
Desafio | Linguagens Permitidas | Nível
--------|-----------------------|------
[Tabuada](/tabuada/README.md) | Todas | Fácil 
[Recursão](/recursao/README.md) | Elixir | Difícil
```

Também podemos usar o nome do desafio como diretório

**Comment by GustavoGarciaPereira** [comment]
achei muito bia a ideia, estava pensando como eu faria isso
